#!/usr/bin/env bash
# Build MiniEreader.app from the SwiftPM executable.
# Use this while you don't have full Xcode installed. Once Xcode is installed,
# the Xcode project (generated by scripts/bootstrap.sh) is the canonical path.
set -euo pipefail

CONFIG="${1:-release}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MAC_DIR="$ROOT/mac"
BUILD_DIR="$ROOT/build"
APP="$BUILD_DIR/MiniEreader.app"

echo "▶ Building (swift build -c $CONFIG)..."
cd "$MAC_DIR"
swift build -c "$CONFIG"

BIN_PATH="$(swift build -c "$CONFIG" --show-bin-path)/MiniEreader"
if [[ ! -f "$BIN_PATH" ]]; then
  echo "✗ Binary not found at $BIN_PATH" >&2
  exit 1
fi

echo "▶ Wrapping into $APP..."
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BIN_PATH" "$APP/Contents/MacOS/MiniEreader"

# Render app icon from code. Keeps the repo free of binary assets.
echo "▶ Rendering icon..."
swift "$ROOT/scripts/make-icon.swift" "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleDisplayName</key><string>Mini E-Reader</string>
    <key>CFBundleName</key><string>Mini E-Reader</string>
    <key>CFBundleExecutable</key><string>MiniEreader</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundleIdentifier</key><string>com.mini-ereader.app</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSLocationUsageDescription</key>
    <string>Mini E-Reader uses your location only to read the current Wi-Fi network name so it can tell when you are connected to the e-reader. Your location is never stored or transmitted.</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Mini E-Reader uses your location only to read the current Wi-Fi network name so it can tell when you are connected to the e-reader. Your location is never stored or transmitted.</string>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsLocalNetworking</key><true/>
    </dict>
</dict>
</plist>
PLIST

# Ad-hoc sign with entitlements so Location permission + network access work.
echo "▶ Ad-hoc signing..."
codesign --force --sign - \
  --entitlements "$MAC_DIR/MiniEreader/MiniEreader.entitlements" \
  --options runtime \
  "$APP"

echo "✓ Built $APP"

# Mirror into /Applications so the user can launch it from Spotlight or
# Launchpad without remembering the build path. rsync preserves the bundle
# structure; we re-sign after because rsync can strip the signature.
INSTALL_APP="/Applications/MiniEreader.app"
if [[ -w /Applications || $EUID -eq 0 ]]; then
  rsync -a --delete "$APP/" "$INSTALL_APP/"
  # Strip provenance / quarantine xattrs — these cause Launchpad/Finder to
  # silently block ad-hoc signed apps even though `open` from the terminal
  # works fine.
  xattr -dr com.apple.quarantine "$INSTALL_APP" 2>/dev/null || true
  xattr -dr com.apple.provenance "$INSTALL_APP" 2>/dev/null || true
  codesign --force --sign - \
    --entitlements "$MAC_DIR/MiniEreader/MiniEreader.entitlements" \
    --options runtime \
    "$INSTALL_APP" >/dev/null 2>&1 || true
  echo "✓ Installed $INSTALL_APP"
fi

echo "  Run: open $APP"
echo "  or:  $APP/Contents/MacOS/MiniEreader   (to see logs)"
